# -*- coding: utf-8 -*-
"""etl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxMZYL1l8lIoagiB3v3sYyNnKUoYzm9y

https://github.com/2521812022/etl-data-pipeline2521812022.git
"""

!pip install sqlalchemy psycopg2-binary

import pandas as pd
from sqlalchemy import create_engine

database_url = "postgresql://etl_qcos_user:ThzIXDIyLJv3Rqb6j0KqfKiPvICFJ2dj@dpg-d6vhs675gffc73dbbv1g-a.oregon-postgres.render.com/etl_qcos"

engine = create_engine(database_url)

try:
    test = pd.read_sql("SELECT 1", engine)
    print("¡Conexión exitosa a la base de datos en Render!")
    print(test)
except Exception as e:
    print("Error de conexión:", e)

import pandas as pd
import numpy as np


url_clientes = "https://raw.githubusercontent.com/2521812022/etl-data-pipeline2521812022/refs/heads/main/data/raw/C_clientes.csv"
url_pagos = "https://raw.githubusercontent.com/2521812022/etl-data-pipeline2521812022/refs/heads/main/data/raw/C_pagos.csv"
url_ventas = "https://raw.githubusercontent.com/2521812022/etl-data-pipeline2521812022/refs/heads/main/data/raw/C_ventas.csv"


clientes = pd.read_csv(url_clientes)
pagos = pd.read_csv(url_pagos)
ventas = pd.read_csv(url_ventas)


print("¡Archivos CSV extraídos exitosamente desde GitHub!")

clientes.head()

def normalizar_columnas(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )
    return df

def limpiar_texto_basico(df):
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace(
            ["nan", "None", "NULL", "null", ""],
            pd.NA
        )
    return df

def eliminar_duplicados(df):
    return df.drop_duplicates()

# 2. Aplicar la limpieza a tus 3 DataFrames
dfs = [clientes, pagos, ventas]

for i in range(len(dfs)):
    dfs[i] = normalizar_columnas(dfs[i])
    dfs[i] = limpiar_texto_basico(dfs[i])
    dfs[i] = eliminar_duplicados(dfs[i])

# Reasignar a las variables correctas
clientes, pagos, ventas = dfs

print("¡Limpieza general completada con éxito!")

# 1. Transformación de formatos (Garantiza que sean fechas y números)
# ----------------------------------------------------------------
ventas['fecha'] = pd.to_datetime(ventas['fecha'], errors='coerce')
ventas['total'] = pd.to_numeric(ventas['total'], errors='coerce')
pagos['monto_pagado'] = pd.to_numeric(pagos['monto_pagado'], errors='coerce')

# 2. Separación de CLIENTES
# -------------------------
clientes_validos = clientes[clientes['cliente'].notna() & clientes['correo'].notna()].copy()
clientes_rechazados = clientes[clientes['cliente'].isna() | clientes['correo'].isna()].copy()

def motivo_c(row):
    m = []
    if pd.isna(row.get('cliente')): m.append("cliente_vacio")
    if pd.isna(row.get('correo')): m.append("correo_vacio")
    return ",".join(m)

if not clientes_rechazados.empty:
    clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo_c, axis=1)

# 3. Separación de VENTAS
# -----------------------
# Regla: Debe tener fecha válida Y total mayor a 0
ventas_validas = ventas[ventas['fecha'].notna() & (ventas['total'] > 0)].copy()
ventas_rechazadas = ventas[ventas['fecha'].isna() | (ventas['total'] <= 0) | ventas['total'].isna()].copy()

if not ventas_rechazadas.empty:
    def motivo_v(row):
        m = []
        if pd.isna(row.get('fecha')): m.append("fecha_invalida_o_vacia")
        if pd.isna(row.get('total')) or row.get('total') <= 0: m.append("total_invalido_o_vacio")
        return ",".join(m)
    ventas_rechazadas['motivo_rechazo'] = ventas_rechazadas.apply(motivo_v, axis=1)

# 4. Separación de PAGOS
# ----------------------
# Regla: El monto pagado debe ser mayor a 0
pagos_validos = pagos[pagos['monto_pagado'] > 0].copy()
pagos_rechazados = pagos[(pagos['monto_pagado'] <= 0) | pagos['monto_pagado'].isna()].copy()

if not pagos_rechazados.empty:
    pagos_rechazados['motivo_rechazo'] = "monto_invalido_o_vacio"

# 5. Exportación masiva de archivos
# ---------------------------------
# Curated (Los que van a la BD)
clientes_validos.to_csv("clientes_curated.csv", index=False)
ventas_validas.to_csv("ventas_curated.csv", index=False)
pagos_validos.to_csv("pagos_curated.csv", index=False)

# Rejects (Los que se quedaron fuera)
clientes_rechazados.to_csv("clientes_rejects.csv", index=False)
ventas_rechazadas.to_csv("ventas_rejects.csv", index=False)
pagos_rechazados.to_csv("pagos_rejects.csv", index=False)

# 6. Resumen de ejecución
# -----------------------
print("--- RESUMEN DE PROCESAMIENTO ETL ---")
print(f"CLIENTES: {len(clientes_validos)} OK | {len(clientes_rechazados)} RECHAZADOS")
print(f"VENTAS:   {len(ventas_validas)} OK | {len(ventas_rechazadas)} RECHAZADOS")
print(f"PAGOS:    {len(pagos_validos)} OK | {len(pagos_rechazados)} RECHAZADOS")
print("------------------------------------")
print("¡Archivos generados y listos para descargar!")

ventas['fecha'] = pd.to_datetime(ventas['fecha'], errors='coerce')

ventas['total'] = pd.to_numeric(ventas['total'], errors='coerce')
pagos['monto_pagado'] = pd.to_numeric(pagos['monto_pagado'], errors='coerce')

pagos.to_csv("pagos_curated.csv", index=False)
ventas.to_csv("ventas_curated.csv", index=False)

print("¡Transformaciones aplicadas correctamente!")

# Carga final a PostgreSQL en la nube
clientes_validos.to_sql('clientes', engine, if_exists='replace', index=False)
ventas_validas.to_sql('ventas', engine, if_exists='replace', index=False)
pagos_validos.to_sql('pagos', engine, if_exists='replace', index=False)

print("¡Base de datos sincronizada con datos 100% validados! 🚀")

print("¡Datos cargados exitosamente a la base de datos en Render! 🚀")

prueba_bd = pd.read_sql("SELECT * FROM ventas LIMIT 5", engine)
print("\nMuestra de la tabla ventas directamente desde PostgreSQL:")
print(prueba_bd)