# -*- coding: utf-8 -*-
"""Parcial2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxMZYL1l8lIoagiB3v3sYyNnKUoYzm9y

https://github.com/2521812022/etl-data-pipeline2521812022.git
"""

!pip install sqlalchemy psycopg2-binary

import pandas as pd
from sqlalchemy import create_engine

database_url = "postgresql://etl_qcos_user:ThzIXDIyLJv3Rqb6j0KqfKiPvICFJ2dj@dpg-d6vhs675gffc73dbbv1g-a.oregon-postgres.render.com/etl_qcos"

engine = create_engine(database_url)

try:
    test = pd.read_sql("SELECT 1", engine)
    print("¡Conexión exitosa a la base de datos en Render!")
    print(test)
except Exception as e:
    print("Error de conexión:", e)

import pandas as pd
import numpy as np


url_clientes = "https://raw.githubusercontent.com/2521812022/etl-data-pipeline2521812022/refs/heads/main/data/raw/C_clientes.csv"
url_pagos = "https://raw.githubusercontent.com/2521812022/etl-data-pipeline2521812022/refs/heads/main/data/raw/C_pagos.csv"
url_ventas = "https://raw.githubusercontent.com/2521812022/etl-data-pipeline2521812022/refs/heads/main/data/raw/C_ventas.csv"


clientes = pd.read_csv(url_clientes)
pagos = pd.read_csv(url_pagos)
ventas = pd.read_csv(url_ventas)


print("¡Archivos CSV extraídos exitosamente desde GitHub!")

clientes.head()

def normalizar_columnas(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )
    return df

def limpiar_texto_basico(df):
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace(
            ["nan", "None", "NULL", "null", ""],
            pd.NA
        )
    return df

def eliminar_duplicados(df):
    return df.drop_duplicates()

# 2. Aplicar la limpieza a tus 3 DataFrames
dfs = [clientes, pagos, ventas]

for i in range(len(dfs)):
    dfs[i] = normalizar_columnas(dfs[i])
    dfs[i] = limpiar_texto_basico(dfs[i])
    dfs[i] = eliminar_duplicados(dfs[i])

# Reasignar a las variables correctas
clientes, pagos, ventas = dfs

print("¡Limpieza general completada con éxito!")

# 1. Separar datos válidos y rechazados (usando 'cliente' y 'correo')
clientes_validos = clientes[
    clientes['cliente'].notna() &
    clientes['correo'].notna()
].copy()

clientes_rechazados = clientes[
    clientes['cliente'].isna() |
    clientes['correo'].isna()
].copy()

# 2. Función para identificar el motivo de rechazo
def motivo(row):
    motivos = []
    if pd.isna(row.get('cliente')):
        motivos.append("cliente_vacio")
    if pd.isna(row.get('correo')):
        motivos.append("correo_vacio")
    return ",".join(motivos)

# 3. Aplicar la función a los rechazados
if not clientes_rechazados.empty:
    clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo, axis=1)

print(f"Clientes válidos: {len(clientes_validos)}")
print(f"Clientes rechazados: {len(clientes_rechazados)}")

# 4. Exportar los archivos sin el índice
clientes_validos.to_csv("clientes_curated.csv", index=False)
clientes_rechazados.to_csv("clientes_rejects.csv", index=False)

# Exportar también pagos y ventas a curated
pagos.to_csv("pagos_curated.csv", index=False)
ventas.to_csv("ventas_curated.csv", index=False)

print("¡Archivos exportados exitosamente en Colab!")

ventas['fecha'] = pd.to_datetime(ventas['fecha'], errors='coerce')

ventas['total'] = pd.to_numeric(ventas['total'], errors='coerce')
pagos['monto_pagado'] = pd.to_numeric(pagos['monto_pagado'], errors='coerce')

pagos.to_csv("pagos_curated.csv", index=False)
ventas.to_csv("ventas_curated.csv", index=False)

print("¡Transformaciones aplicadas correctamente!")

# 1. Cargar clientes válidos a Render
clientes_validos.to_sql('clientes', engine, if_exists='replace', index=False)

# 2. Cargar ventas a Render
ventas.to_sql('ventas', engine, if_exists='replace', index=False)

# 3. Cargar pagos a Render
pagos.to_sql('pagos', engine, if_exists='replace', index=False)

print("¡Datos cargados exitosamente a la base de datos en Render! 🚀")

# --- Comprobación rápida ---
# Leemos un par de registros directamente desde la nube para verificar que todo llegó bien
prueba_bd = pd.read_sql("SELECT * FROM ventas LIMIT 5", engine)
print("\nMuestra de la tabla ventas directamente desde PostgreSQL:")
print(prueba_bd)